lib/cunit/cu_pc_patch.c
This PR fixes a compilation issue when GHT support is activated. Moreover, I fixed the indentation in the corresponding unit test function.
=> fix compilation issue with GHT support

lib/lazperf_adapter.h, lib/lazperf_adapter.hpp, lib/pc_api_internal.h, lib/pc_filter.c, lib/pc_patch.c, lib/pc_patch_lazperf.c
This PR fixes a number of warnings at compile time.
=> Fix a number of compile warnings

CMakeLists.txt, README.md
=> Add check and installcheck targets to CMake-based Makefile

lib/pc_schema.c, lib/pc_util.c
This is a fix style only patch.
=> Remove tabs within if statements

README.md
This PR suggests a number of fixes and improvements to the documentation.
=> Fixes and improvements to the README file

README.md
I tend to forget what I need to do for running the SQL Tests (yes, I know…). Hence this addition to the README file…
=> Add an SQL Tests section to README.md

lib/cunit/cu_pc_patch.c, lib/pc_api_internal.h, lib/pc_patch.c, lib/pc_patch_lazperf.c, pgsql/expected/pointcloud-laz.out, pgsql/sql/pointcloud-laz.sql
This PR : 
- adds laz support within the PC_PointN function
- update the NEWS file by adding the PC_PointN function with its corresponding PR number
=> PC_PointN : add laz support and update NEWS file

NEWS, README.md, lib/cunit/cu_pc_patch.c, lib/cunit/cu_pc_schema.c, lib/pc_api.h, lib/pc_patch.c, lib/pc_schema.c, pgsql/expected/pointcloud.out, pgsql/pc_editor.c, pgsql/pointcloud.sql.in, pgsql/sql/pointcloud.sql
This adds a `PC_Transform` function to transform a patch based on new schema.
This is still WIP at the moment.
=> Add PC_Transform

README.md
=> Improve PDAL pipeline in README

.travis.yml
See https://github.com/travis-ci/travis-ci/issues/6972
=> Work-around for travis trusty postgis problem

pgsql/pc_pgsql.c
This is an attempt to fix a memory corruption reported with https://github.com/pgpointcloud/pointcloud/issues/71#issuecomment-368228150.
This comes from a patch I wrote a long time ago, but that I didn't create a PR for. I just tested it, and it seems to fix the problem.
=> Remove the generic cache

README.md, lib/cunit/cu_pc_patch.c, lib/pc_api.h, lib/pc_point.c, pgsql/expected/pointcloud.out, pgsql/pc_access.c, pgsql/pc_inout.c, pgsql/pointcloud.sql.in, pgsql/sql/pointcloud.sql
Add PC_MakePatch to create a patch from a pcid and an array of float8 values.
Supersedes #219.
=> Add PC_MakePatch(pcid integer, values float8[])

README.md
Fixes https://github.com/pgpointcloud/pointcloud/issues/230
=> Update readme with pc_memsize documentation

pgsql/pc_access.c, pgsql/pc_pgsql.c, pgsql/pc_pgsql.h
I copied this from fix we did in PostGIS. 
Note I confirmed it compiles but since I don't have lazperz tests often fail for me.
https://trac.osgeo.org/postgis/ticket/4313
=> Support for PostgreSQL 12 references #243

.gitignore, docker/Dockerfile, docker/initdb-pgpointcloud.sh
When starting a docker container, the database will now be automatically initialized with the postgis and pointcloud extensions, similar to [postgis dockerfile](https://github.com/postgis/docker-postgis).
=> added database initialization script to dockerfile

.github/workflows/website.yml
Use the latest sphinx version to generate the HTML documentation.
=> Update HTML documentation

.github/scripts/test_dump_restore.sh, .github/scripts/test_dump_restore.sql, .github/workflows/bionic_postgres10_postgis25.yml, .github/workflows/bionic_postgres11_postgis25.yml, .github/workflows/bionic_postgres12_postgis25.yml, .github/workflows/bionic_postgres12_postgis32.yml, .github/workflows/focal_postgres12_postgis32.yml, .github/workflows/focal_postgres13_postgis32.yml, .github/workflows/focal_postgres14_postgis32.yml, pgsql/expected/pointcloud.out, pgsql/pc_pgsql.c, pgsql/pc_pgsql.h, pgsql/pointcloud.control.in, pgsql/pointcloud.sql.in, pgsql_postgis/pointcloud_postgis.control.in, pgsql_postgis/pointcloud_postgis.sql.in
Fixes https://github.com/pgpointcloud/pointcloud/issues/197 https://github.com/pgpointcloud/pointcloud/issues/211
TODO:
=> Fix dump and restore

pgsql/pc_access.c, pgsql/pc_pgsql.c, pgsql/pc_pgsql.h
Partial correction for https://github.com/pgpointcloud/pointcloud/issues/313
=> Fixes uninitialised schema cache during first call

lib/pc_patch.c, lib/pc_patch_dimensional.c
Fixes https://github.com/pgpointcloud/pointcloud/issues/282
=> No crash when invalid dimensional patch

pgsql/pc_editor.c
=> Fix segmentation fault in pcpatch_transform

.github/scripts/postgresql_postgis.sh, .github/workflows/focal_postgres15_postgis32.yml, README.md, doc/development.rst, pgsql/pc_inout.c
Fixes https://github.com/pgpointcloud/pointcloud/issues/314
=> PG15 support (with CI)

.cirrus.yml
This allows to test on something else than gnu/linux/gcc. :kissing_heart: :smiling_imp:
=> Add FreeBSD CI with cirrus

configure.ac
Fixes https://github.com/pgpointcloud/pointcloud/issues/366
=> Fix autoconf warnings
