pgsql/CMakeLists.txt
=> Remove hard-coded version number from cmake build script

lib/CMakeLists.txt
On Ubuntu precise64, gcc/g++ 4.8, cmake 2.8.11.2, I get a link error between the static libpc and the (default shared) libpointcloud.so. This patch fixes the link error.
Fixes #26
=> Compile the static library with -fPIC

lib/CMakeLists.txt, pgsql/CMakeLists.txt
CMake install is broken w/o this patch. Depends on #55 (which fixes cmake build).
=> Configure cmake files to fix cmake install

lib/cunit/cu_pc_bytes.c, lib/pc_bytes.c
Output compression was erroneously set to PC_DIM_SIGBITS instead of PC_DIM_NONE. Thanks @pblottiere for spotting this!
=> pc_bytes_sigbits_decode compression -> PC_DIM_NONE

.travis.yml, lib/cunit/cu_pc_bytes.c, lib/pc_schema.c, lib/pc_val.c
steps towards addressing #100 :
=> valgrind-clean

lib/cunit/cu_pc_schema.c, lib/cunit/data/simple-schema-empty-field.xml, lib/pc_schema.c
A segmentation fault occurs and crash postgresql when a child node is empty in a PC schema definition.
This PR tries to fix that. 
Tested only against PostgreSQL 9.5.
=> fix crash when a child node is empty in pc schema

README.md, lib/cunit/cu_pc_patch.c, lib/pc_api.h, lib/pc_api_internal.h, lib/pc_bytes.c, lib/pc_patch.c, lib/pc_patch_dimensional.c, lib/pc_patch_ght.c, lib/pc_patch_uncompressed.c, pgsql/pc_access.c, pgsql/pointcloud.sql.in
This PR adds a PostgreSQL pointcloud equivalent of [ST_PointN](http://postgis.net/docs/ST_PointN.html)
PC_PointN(patch pcpatch, n int4) : pcpoint
get point `n`-th from patch (LI3DS/pointcloud#14)
- first point : `1` or `-PC_NumPoints(patch)`
- last point : `-1` or `PC_NumPoints(patch)`
Native implementations other compressions relying on uncompression :
- functionalities : @mbredif
- tests : @pblottiere
=> new PC_PointN function

CMakeLists.txt, pgsql/CMakeLists.txt
Fixes issue #118.
pgpointcloud is C, it should be using CLFAGS not CPPFLAGS.
=> Fix compile against PostgreSQL 9.6 on Debian by using correct flags.

lib/cunit/cu_pc_bytes.c, lib/cunit/cu_pc_patch.c, lib/cunit/cu_pc_patch_ght.c, lib/cunit/cu_pc_patch_lazperf.c, lib/cunit/cu_pc_point.c, lib/cunit/cu_pc_schema.c
The `cu_tester` binary currently segfaults on Debian 9 (Sid). This is because Debian 9 has CUnit 2.1-3, in which the `CU_SuiteInfo` structure has changed.
This PR changes the unit test code in a way that it works with both CUnit 2.1-2 and 2.1-3.
=> Fix unit tests with cunit 2.1-3

lib/pc_api.h, pgsql/pc_pgsql.c
This commit adds `__attribute__ ((format (printf, x, y)))` where it makes sense.
This removes the following compile warning:
```
[ 96%] Building C object pgsql/CMakeFiles/pointcloud.dir/pc_pgsql.c.o
/home/elemoine/src/pointcloud/pgsql/pc_pgsql.c: In function ‘pgsql_msg_handler’:
/home/elemoine/src/pointcloud/pgsql/pc_pgsql.c:66:2: warning: function might be possible candidate for ‘gnu_printf’ format attribute [-Wsuggest-attribute=format]
vsnprintf(msg, MSG_MAXLEN, fmt, ap);
^~~~~~~~~
```
The compilation is warning-free after this for me!
I hesitated to create a macro for this, so that we don't use `__attribute__` when the compiler is not GNUC. But I am not sure pgpointcloud actually supports other compilers.
=> Use __attribute__ ((format (printf, x, y)))

lib/cunit/cu_pc_bytes.c, lib/cunit/cu_pc_patch_ght.c, lib/cunit/cu_pc_point.c, lib/pc_patch_ght.c, lib/pc_patch_lazperf.c
When using autotools (as opposed to cmake) the `-Wunused-variable` flag is used, revealing that a number of functions and variables are not used. This PR removes the unused functions and variables.
There's actually one left in `pc_patch.c`:
```
gcc -Wall -O2 -g -fPIC -I/usr/include/libxml2  -I/home/elemoine/local/include -I/home/elemoine/local/include/  -c -o pc_patch.o pc_patch.c                                                                         
pc_patch.c: In function ‘pc_patch_compress’:                                                                                                                                                                       
pc_patch.c:248:21: warning: unused variable ‘pal’ [-Wunused-variable] …
```
=> Remove unused functions and vars

NEWS, README.md, lib/CMakeLists.txt, lib/Makefile, lib/cunit/CMakeLists.txt, lib/cunit/Makefile, lib/cunit/cu_pc_sort.c, lib/cunit/cu_tester.c, lib/pc_api.h, lib/pc_sort.c, lib/sort_r/README.md, lib/sort_r/sort_r.h, pgsql/pc_access.c, pgsql/pointcloud.sql.in
(This is a rebased version of #102, taking into account @pramsey's PCDIMENSION_LIST comment)
This pull request proposes 2 new interrelated functions:
- `PC_Sort( pcpatch, text[] ) : pcpatch`
- `PC_IsSorted( pcpatch, text[], boolean ) : boolean`
(pgpointcloud/pointcloud#54, LI3DS/pointcloud#10) 
Lexicographically sort a patch `pa` on the given dimensions `attr`.
What is natively implemented ?
(LI3DS/pointcloud#9)
Test whether a patch `pa` is lexicographically sorted on the given dimensions `attr`.
The `strict` option requires strict sorting (no duplicates).
What is natively implemented ?
- functionalities : @mbredif
- tests : @pblottiere
=> PC_Sort and PC_IsSorted

lib/cunit/cu_pc_sort.c
cu_pc_sort.c currently uses a mix of spaces and tabs. This commit changes all the tabs to spaces.
=> Fix indent in cu_pc_sort.c

lib/cunit/cu_pc_patch_lazperf.c
When using `./configure CFLAGS="-Wall -O2 -g"` we get an "unused-function" warning at compile time. This was raised by @strk in #130. This commit fixes the issue.
=> Remove compile warning

lib/pc_api.h, lib/pc_api_internal.h, lib/pc_patch_ght.c, lib/pc_patch_lazperf.c, lib/pc_patch_uncompressed.c, lib/pc_pointlist.c
@elemoine , @strk, this is an alternative PR to #135, with cleaner semantics (I think).
- The readonly attribute of pointlist was never used. I propose to change it for an opaque memory pointer `mem`, that will point to the data owned by the pointlist, if any so that it can be freed upon destruction.
- The new function `pc_patch_uncompressed_readonly` makes the patch readonly and return the disowned `data`, if any, to enable transfer ownership (eg: affectation to the `pointlist->mem` pointer
- As a bonus, pc_pointlist_from_dimensional can now be implemented with a single pcalloc/patch rather than point.
=> pointlist memory fix, pc_pointlist_from_dimensional memory optimization

lib/pc_point.c
A typo was introduced while rebasing this PR: `z` values were assigned to both `z` and `m` output points
=> pc_point_to_geometry_wkb : get_m fix

lib/cunit/cu_pc_patch_lazperf.c, lib/pc_filter.c
In `pc_patch_filter`, when `nset` is `0`, the empty patch returned was created with an invalid maxpoints value in the case of lazperf.
=> Fix bug in pc_patch_filter for lazperf

lib/cunit/cu_pc_patch_lazperf.c, lib/cunit/data/simple-schema-laz-multiple-dim.xml, lib/lazperf_adapter.cpp, pgsql/expected/pointcloud-laz.out, pgsql/expected/pointcloud.out, pgsql/sql/pointcloud-laz.sql
This PR fixes three issues in laz support:
- the lack of support for PC_INT64, PC_UINT64, PC_DOUBLE, and PC_FLOAT for laz compression
- a memory error due to a too soon free in the lifecycle of a PCPOINTLIST coming from a lazperf patch
- a pgsql expected output for laz tests
=> fix laz support (memory issue and lack in lazperf type)

configure.ac
This tiny patch changes a non-breaking space character to a regular space character in `configure.ac`.
=> Change non-breaking space to regular space

.travis.yml
eclint 2 was recently released. Unfortunately this version is not compatible with the version of NodeJS available on Travis. So let's stick to eclint 1.1.5 for now.
=> Use eclint 1.1.5

NEWS, README.md, lib/cunit/cu_pc_patch.c, lib/pc_api.h, lib/pc_patch.c, pgsql/expected/pointcloud.out, pgsql/pc_access.c, pgsql/pointcloud.sql.in, pgsql/sql/pointcloud.sql
This commit adds a `PC_Range` function. This function returns a patch of "count" points. These points are selected from the start-th point in the input patch.
Patch originally written by @pblottiere.
=> Add PC_Range(p PCPATCH, first int4, count int4)

README.md, pgsql/expected/pointcloud.out, pgsql/pc_inout.c, pgsql/pointcloud.sql.in, pgsql/sql/pointcloud.sql, pgsql_postgis/pointcloud_postgis--1.0.sql
Following #30 and #86, I propose this simple PR concerning the SQL api.
It basically renames `PC_Envelope` as `PC_EnvelopeAsBinary`, which properly states what it does, leaving room to rename `geometry(pcpatch)` as `PC_Envelope(pcpatch)`.
The cast PCPATCH::geometry is removed since it is ambiguous with the 3D or 4D geometry exports (3D envelope, some 4D geometry to give access to the 4D bbox...) that have been made possible by the recent support for ZM dimensions.
=> PC_EnvelopeAsBinary -> bytea, PC_Envelope -> geometry

.travis.yml
This PR adds `-Werror` to `CFLAGS` on Travis. This is to avoid merging code that introduces new compile warnings.
=> Compile with -Werror on Travis

NEWS, README.md, lib/cunit/CMakeLists.txt, lib/cunit/Makefile, lib/cunit/cu_pc_util.c, lib/cunit/cu_tester.c, lib/pc_api.h, lib/pc_api_internal.h, lib/pc_stats.c, lib/pc_util.c, pgsql/expected/pointcloud.out, pgsql/pc_inout.c, pgsql/pointcloud.sql.in, pgsql/sql/pointcloud.sql, pgsql_postgis/pointcloud_postgis--1.0.sql
This provides a `PC_BoundingDiagonal` function that can be used to get the 2D, Z, M or ZM bounding diagonal of a patch. Using this function indices on `PC_BoundingDiagonal(patch)` can be created, making 3D spatial relationship tests possible.
@mbredif @pblottiere does this correspond to what we discussed?
Todo:
=> Add PC_BoundingDiagonal(p PCPATCH)

pgsql/pointcloud.sql.in
Type I/O functions should not be volatile. PostgreSQL 9.5 and above include a test for this, yielding this warning when a volatile function is detected:
WARNING:  type input function pointcloud_abs_in should not be volatile
This commit makes pointcloud_abs_out and pointcloud_abs_in, which are currently empty shells, non-volatile.
Fixes https://github.com/pgpointcloud/pointcloud/issues/93.
=> Make pointcloud_abs_out|in immutable and strict

NEWS, README.md, lib/cunit/cu_pc_patch.c, lib/cunit/data/simple-schema-no-intensity.xml, lib/pc_api.h, lib/pc_patch.c, lib/pc_val.c, pgsql/CMakeLists.txt, pgsql/Makefile, pgsql/expected/pointcloud.out, pgsql/pc_editor.c, pgsql/pointcloud.sql.in, pgsql/sql/pointcloud.sql
This PR is a clean version of https://github.com/pgpointcloud/pointcloud/pull/154, taking into account all the review comments and with one squashed commits instead of 19.
Commit message:
Add PC_SetPCId
This commit adds a `PC_SetPCId` function that can be used to change the schema of a patch.
=> Add PC_SetPCId

pgsql/pc_editor.c
The case of the characters should be ignored when comparing dimension names in pcpatch_schema_same_dimensions. This is to match the behavior of pc_schema_get_dimension_by_name which ignores the case.
=> Ignore case where comparing dimension names

pgsql_postgis/pointcloud_postgis--1.0.sql
For backward-compatibility reasons this commit adds back the `geometry(pcpatch)` function that was removed with 7da35f0. This function is just an alias to `PC_Envelope(pcpatch)`.
=> Add the geometry(pcpach) function back

README.md, pgsql/expected/pointcloud.out, pgsql/pc_inout.c, pgsql/pointcloud.sql.in, pgsql/sql/pointcloud.sql, pgsql_postgis/pointcloud_postgis--1.0.sql
This commits adds `PC_Envelope` back to the pointcloud extension. This is to address the backward-compatibility issue raised in #168.
=> Add PC_Envelope back to the pointcloud extension

lib/cunit/cu_pc_patch.c, lib/pc_patch_ght.c
This PR fixes compilations errors in the pointcloud ght code. We don't builld with libght enabled on Travis, so we do not always see errors.
Fixes #175.
=> Fix compilation with libght

.install-libght.sh, .travis.yml, tools/build-install.sh, tools/valgrind.sh
#175 has reported that we've broken the build when libght is enabled. The problem is that we don't currently build with libght enabled on Travis. This PR is a resurrection of #134 and suggests to build and run unit tests with libght enabled on Travis.
Depends on #176, which should be merged first.
=> Build and test with libght in Travis

lib/cunit/cu_pc_patch.c, lib/cunit/cu_pc_point.c, lib/cunit/cu_pc_sort.c, lib/cunit/cu_pc_util.c, lib/pc_api.h, lib/pc_patch.c, lib/pc_util.c, pgsql/pc_pgsql.c
This PR does two things.
1. It greatly improves the performance of the `hexbytes_from_bytes` performance by avoiding calling `snprintf` for each byte. The implementation is now [similar](https://github.com/postgis/postgis/blob/svn-trunk/liblwgeom/lwout_wkb.c#L34-L58) to PostGIS.
1. It adds a `pc_` prefix to the `bytes_from_hexbytes`, `hexbytes_from_bytes` and `wkb_get_pcid` functions to avoid conflicts with other libraries like PostGIS.
Together, these two commits fix a major performance bug. See the [discussion](https://www.postgresql.org/message-id/flat/49f41956-f50b-9551-1943-6e12ed12fa29%40oslandia.com#49f41956-f50b-9551-1943-6e12ed12fa29@oslandia.com) on the pgsql-general mailing list and the [test case](https://github.com/elemoine/pgpc-perf) for more detail.
=> Make hexbytes_from_bytes perform better

CMakeLists.txt, lib/CMakeLists.txt
This makes pgpointcloud actually use information provided by find_package() for zlib and libxml2.
The mention of ${LIBXML2_INCLUDE_DIR} is left for compatibility since it was only included in CMake 3.7.2.
=> Use proper CMake idioms for libxml2 and zlib.

lib/sort_r/sort_r.h
Adapted from upstream commit 1eb3da5945bfb753b56e389379795f1408b152e1
Fixes #186
=> Define inline for all systems, change for Windows to __inline

pgsql/pointcloud.sql.in
This removes the "stat text default" argument from the PC_PatchMin, PC_PatchMax and PC_PatchAvg functions. This argument is not used, and it causes performance issues as reported in https://github.com/pgpointcloud/pointcloud/issues/187.
With this, after upgrading, the PC_PatchMin, PC_PatchMax and PC_PatchAvg functions with the previous signature (with three arguments) will be preserved. DROP FUNCTION PC_PatchXXX(pcpatch, text, text) should be used to drop them.
=> Remove "stat text default" argument

.gitignore, configure.ac, pgsql/pc_access.c, pgsql/pointcloud.sql.in, pgsql_postgis/Makefile, pgsql_postgis/pointcloud_postgis.control.in, pgsql_postgis/pointcloud_postgis.sql.in
This PR does two things:
- make the versions of the pointcloud and pointcloud_postgis extensions the same
- add a pc_full_version function that includes more information than just the pointcloud version
This is what pc_full_version returns:
```
pc_full_version
------------------------------------------------------------------------------------------
POINTCLOUD="1.1.0" PGSQL="96" LIBXML2="2.9.4" LIBGHT enabled=false LAZPERF enabled=false
(1 row)
```
@robe2 is that what you had in mind?
=> Better handling of versions

lib/cunit/cu_pc_patch.c, lib/pc_api_internal.h, lib/pc_patch.c, lib/pc_patch_dimensional.c, lib/pc_patch_ght.c, lib/pc_patch_lazperf.c, lib/pc_patch_uncompressed.c
This PR replaces https://github.com/pgpointcloud/pointcloud/pull/112.
I've taken @achidlow's commits, squashed them together, and added three additional commits. My second commit renames the pc_patch_common_free function to pc_patch_free_stats, which is more explicit.
@mbredif can you please take a final look at this before I merge it and release 1.1.0?
=> Fix pc_patch_compress leak (take 2)

configure.ac
Some AC_DEFINE returns warnings:
> 
> autoheader-2.69: warning: missing template: HAVE_CUNIT
> autoheader-2.69: Use AC_DEFINE([HAVE_CUNIT], [], [Description])
> autoheader-2.69: warning: missing template: HAVE_LAZPERF
> autoheader-2.69: warning: missing template: HAVE_LIBGHT
> autoheader-2.69: warning: missing template: PROJECT_SOURCE_DIR
> autoreconf-2.69: /usr/local/bin/autoheader-2.69 failed with exit status: 1
> *** Error code 1
Needed to package pointcloud 1.1.0 in FreeBSD.
=> Adds missing description in AC_DEFINE

pgsql/pc_pgsql.c
Using -Wall and -O2 gcc 8.2.0 warns us about memcpy's that are out-of-bounds.
```
In file included from /usr/include/string.h:494,
from ../lib/pc_api.h:18,
from pc_pgsql.h:12,
from pc_pgsql.c:14:
In function ‘memcpy’,
inlined from ‘pc_patch_wkb_set_int32’ at pc_pgsql.c:863:2,
inlined from ‘pc_patch_to_geometry_wkb_envelope’ at pc_pgsql.c:918:8:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:10: warning: ‘__builtin_memcpy’ forming offset [5, 8] is out of the bounds [0, 4] of object ‘i’ with type ‘uint32_t’ {aka ‘unsigned int’} [-Warray-bounds]
return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
gcc is correct, there is a bug in pc_patch_wkb_set_int32. We should copy 4 bytes instead of 8 bytes.
=> Fix memcpy size in pc_patch_wkb_set_int32

pgsql/pc_access.c, pgsql/pc_inout.c
This PR fixes #236 
The following commit in PostgreSQL [2eb4a831e5fb5d8fc17e13aea56e04af3efe27b4](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=2eb4a831e5fb5d8fc17e13aea56e04af3efe27b4) changed from uppercase to lowercase.
This PR changes the case of boolean values where it is needed to be able to compile.
=> Fix boolean case errors when compiling againt pg11

config.mk.in
Spotted by Debian's build log hardening checker (blhc).
=> Don't overwrite CXXFLAGS from environment

docker/Dockerfile
Supersede https://github.com/pgpointcloud/pointcloud/pull/182.
Add a Dockerfile based on [official PostgreSQL 12 image](https://hub.docker.com/_/postgres/) with PostGIS 3 and lazperf support.
=> Add Dockerfile with PostgreSQL 12 and PostGIS 3

configure.ac
Fixes https://github.com/pgpointcloud/pointcloud/issues/268 
The minor version of PostgreSQL is wrongly detected in some cases. For example on PostgreSQL 13 beta1 release:
``` bash
$ pg_config --version
PostgreSQL 13beta1 (Debian 13~beta1-1.pgdg100+1)
$ ./configure
...
PointCloud is now configured for
-------------- Compiler Info -------------
C compiler:           gcc -g -O2
SQL preprocessor:     /usr/bin/cpp -traditional-cpp -w -P
-------------- Dependencies --------------
PostgreSQL config:    /usr/bin/pg_config
PostgreSQL version:   PostgreSQL 13beta1 (Debian 13~beta1-1.pgdg100+1) (13PostgreSQL 13beta1 (Debian 13~beta1)
Libxml2 config:       /usr/bin/xml2-config
Libxml2 version:      2.9.4
LazPerf status:       disabled
CUnit status:         disabled
```
In this case the version is …
=> Ignore minor version for postgresql >= 9

pgsql/pc_pgsql.c
SPI_connect() opens a new memory context, which is then destroyed by
SPI_finish(). Since we are invoking quote_qualified_identifier()
inbetween, which pallocs its result in that memory context, we cannot
use "formats" in the error messages because that pointer has already
been freed by then. Fix by dropping all SPI_finish() calls in paths that
elog(ERROR) which do handle the memory cleanup anyway.
=> Don't call SPI_finish() when erroring out

.github/scripts/postgresql_postgis.sh, .github/workflows/jammy_postgres16_postgis3.yml, pgsql/pc_pgsql.c
The pg16 does not yet have PostGIS, but tests pass.
So I'm labeling this a WIP since I will change to install PostGIS once PostGIS is available in apt.postgresql.org
=> WIP: Pg16 tests

configure.ac
Addresses a CUnit configuration bug.
Configuring with CUnit present on system, but with `--without-cunit` flag leads to non-sensical compiling flags:
```
CUNIT_CPPFLAGS='-Ino/include'
CUNIT_LDFLAGS='-Lno/lib -lcunit'
```
=> Honor '--without-cunit' configure flag

doc/development.rst, doc/install.rst
Fixes https://github.com/pgpointcloud/pointcloud/issues/352
=> Add instructions to enable laz-perf support
